# HANDLING DUPLICATE DATA

In [4]:
import pandas as pd

In [5]:
data = {"name":["a","b","c","d","a","c"],"eng":[2,3,4,5,2,8],"hindi":[6,5,4,7,6,2]}

In [6]:
df = pd.DataFrame(data)
df

  name  eng  hindi
0    a    2      6
1    b    3      5
2    c    4      4
3    d    5      7
4    a    2      6
5    c    8      2

In [7]:
df.duplicated()

0    False
1    False
2    False
3    False
4     True
5    False
dtype: bool

In [10]:
# df.drop_duplicates(keep="first")
df.drop_duplicates(inplace=True)

In [11]:
df

  name  eng  hindi
0    a    2      6
1    b    3      5
2    c    4      4
3    d    5      7
5    c    8      2

In [12]:

dataset = pd.read_csv(r"C:\Users\SHAMSHER\Downloads\student-lifestyle-and-stress-dataset.csv")
dataset.head(3)

,Student_Type,Sleep_Hours,Study_Hours,Social_Media_Hours,Attendance,Exam_Pressure,Family_Support,Month,Stress_Level
0,school,6.868702,1.711722,3.176942,NaN,8.0,7.0,2.0,1
1,school,8.519088,3.251084,3.880787,93.978465,6.0,4.0,3.0,1
2,college,4.498770,6.306885,2.936172,64.421253,7.0,1.0,12.0,1

In [16]:
dataset.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
25495    False
25496    False
25497    False
25498    False
25499    False
Length: 25500, dtype: bool

In [15]:
dataset.shape

(25500, 9)

In [17]:
dataset.drop_duplicates()

,Student_Type,Sleep_Hours,Study_Hours,Social_Media_Hours,Attendance,Exam_Pressure,Family_Support,Month,Stress_Level
0,school,6.868702,1.711722,3.176942,NaN,8.0,7.0,2.0,1
1,school,8.519088,3.251084,3.880787,93.978465,6.0,4.0,3.0,1
2,college,4.498770,6.306885,2.936172,64.421253,7.0,1.0,12.0,1
3,school,8.591223,2.384922,5.222832,81.868960,2.0,7.0,7.0,0
4,college,5.329293,9.345179,7.815869,85.847982,5.0,6.0,10.0,1
...,...,...,...,...,...,...,...,...,...
25495,college,7.803069,7.328193,2.018277,75.435607,5.0,1.0,12.0,0
25496,school,6.734607,2.680109,3.355559,63.387386,8.0,9.0,2.0,1
25497,college,7.701671,2.631250,2.948252,79.818930,4.0,3.0,4.0,1
25498,school,5.903426,3.450424,6.823894,96.680773,2.0,6.0,6.0,0
25499,college,7.419726,6.442748,3.356066,81.452460,9.0,5.0,6.0,1

In [18]:
dataset.shape

(25500, 9)